### ISSUE TITLE
Test failure where page is already locked

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#331] opened 2014-04-08 12:52 UTC
Tests run: 22, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 36.337 sec <<< FAILURE! - in ch.entwine.weblounge.contentrepository.fs.FileSystemContentRepositoryTest
testLock(ch.entwine.weblounge.contentrepository.fs.FileSystemContentRepositoryTest)  Time elapsed: 0.959 sec  <<< ERROR!
java.lang.IllegalStateException: The page is already locked by 
    at ch.entwine.weblounge.common.impl.content.ResourceImpl.lock(ResourceImpl.java:894)
    at ch.entwine.weblounge.contentrepository.impl.operation.LockOperationImpl.apply(LockOperationImpl.java:83)
    at ch.entwine.weblounge.contentrepository.impl.AbstractWritableContentRepository.get(AbstractWritableContentRepository.java:322)
    at ch.entwine.weblounge.contentrepository.impl.AbstractWritableContentRepository.isLocked(AbstractWritableContentRepository.java:464)
    at ch.entwine.weblounge.contentrepository.fs.FileSystemContentRepositoryTest.testLock(FileSystemContentRepositoryTest.java:917)

**Comment by myniva** [comment] 2016-04-18 16:05
duplicate of #369

**Closed as completed by myniva** 2016-04-18 16:05 UTC
Labels: bug
