### ISSUE TITLE
Test whether the asynchronous repository api is still required

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#294] opened 2013-08-13 16:52 UTC
The asynchronous api has been introduced because the original search implementation (Solr). After introducing JCR, it may make sense for us to test whether those asynchronous methods are still needed and/or whether they can be removed.

**Comment by myniva** [comment] 2016-04-18 16:07
duplicate of #381

**Closed as completed by myniva** 2016-04-18 16:07 UTC
Labels: repository
