### ISSUE TITLE
Quartz job sometimes can't be scheduled

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#18] opened 2012-07-24 08:33 UTC
It seems that the OSGi bundle of Quartz is keeping track of certain jobs, so they are still in the system after a restart. The _real_ problem however seems to be that there are cases, where jobs are not being removed from the scheduler either when the scheduler itself goes down or the site.

```
11:43:54 ERROR (SiteImpl:1373) Error trying to schedule job 'greeter': Unable to store Job with name: 'greeter' and group: 'site weblounge-test', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job with name: 'greeter' and group: 'site weblounge-test', because one already exists with this identification.

at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:221)
at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:193)
at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:803)
at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:243)
at ch.entwine.weblounge.common.impl.site.SiteImpl.scheduleJob(SiteImpl.java:1365)
at ch.entwine.weblounge.common.impl.site.SiteImpl.start(SiteImpl.java:823)
at ch.entwine.weblounge.test.site.TestSite.start(TestSite.java:72)
``
```

**Comment by ghost** [comment] 2012-08-07 16:39
Cannot reproduce anymore.

**Comment by myniva** [comment] 2013-09-19 09:13
Just came across this error again. Steps to reproduce:
1. Start Weblounge with a site which holds one or more jobs
2. Replace a bundle the site is depending on (in my case it was weblounge-contentrepository)

The site goes down and this error occurs while the site is starting again.

**Comment by myniva** [comment] 2013-09-19 09:15
Maybe we should replace our own job scheduling code by a third-party solution. Sling Scheduler looks promising (http://sling.apache.org/documentation/bundles/scheduler-service-commons-scheduler.html)

**Comment by myniva** [comment] 2013-09-22 14:26
Won't fix, because Apache Sling Scheduler is now integrated (see #298). The self-made solution is deprecated.

**Closed as completed by myniva** 2013-09-22 14:26 UTC
Labels: bug
