### ISSUE TITLE
Hang after publishing of endpoints

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#333] opened 2014-04-19 11:45 UTC
Sometimes, when starting Weblounge, the system hangs while/after publishing the endpoints:

vl-01.localdomain | 2014-03-28 15:16:30 INFO (SearchIndexImpl:668) - Starting local Elasticsearch node
vl-01.localdomain | 2014-03-28 15:16:36 INFO (ContentRepositoryServiceFactory:143) - Default content repository implementation is ch.entwine.weblounge.contentrepository.impl.fs.FileSystemContentRepository
vl-01.localdomain | 2014-03-28 15:16:36 INFO (EnvironmentService:164) - Runtime environment set to 'development'
vl-01.localdomain | 2014-03-28 15:16:37 INFO (WebloungeKernel:53) - Starting common weblounge services
vl-01.localdomain | 2014-03-28 15:16:37 INFO (WebloungeKernel:57) - Starting job scheduler
vl-01.localdomain | 2014-03-28 15:16:37 INFO (SharedHttpContextImpl:113) - Enabling requests to protected resources
vl-01.localdomain | 2014-03-28 15:16:37 INFO (SharedHttpContextImpl:61) - Publishing shared http context
vl-01.localdomain | 2014-03-28 15:16:37 INFO (DispatcherServiceImpl:100) - Activating weblounge dispatcher
vl-01.localdomain | 2014-03-28 15:16:38 INFO (WebloungeSharedResources:179) - Serving shared resources at /weblounge-shared
vl-01.localdomain | 2014-03-28 15:16:38 INFO (EndpointPublishingService:124) - Starting rest publishing service

**Comment by myniva** [comment] 2014-08-20 06:29
This is a duplicate of #290

**Closed as completed by myniva** 2014-08-20 06:29 UTC
Labels: bug
