### ISSUE TITLE
Parser error throws exception

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#182] opened 2012-12-03 12:05 UTC
2012-12-03 12:42:56 ERROR (WebloungeDispatcherServlet:363) Request handler 'file request handler' failed to handle /%20http://www.asics.com -
2012-12-03 12:42:56 ERROR (WebloungeDispatcherServlet:367) Path /%20http://www.asics.com cannot be parsed
java.lang.IllegalArgumentException: Path /%20http://www.asics.com cannot be parsed
        at ch.entwine.weblounge.common.impl.url.WebUrlImpl.analyzePath(WebUrlImpl.java:513)
        at ch.entwine.weblounge.common.impl.url.WebUrlImpl.<init>(WebUrlImpl.java:107)
        at ch.entwine.weblounge.common.impl.request.WebloungeRequestImpl.getUrl(WebloungeRequestImpl.java:258)
        at ch.entwine.weblounge.dispatcher.impl.handler.FileRequestHandlerImpl.service(FileRequestHandlerImpl.java:87)
        at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:346)

**Comment by myniva** [comment] 2012-12-04 19:59
Duplicate of #157

**Closed as completed by myniva** 2012-12-04 19:59 UTC
Labels: bug
