### ISSUE TITLE
Random test failures in FileSystemContentRepositoryTes

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#330] opened 2014-03-15 14:54 UTC
This test sometimes succeeds, sometimes doesn't.

testLock(ch.entwine.weblounge.contentrepository.fs.FileSystemContentRepositoryTest)  Time elapsed: 1.318 sec  <<< ERROR!
java.lang.IllegalStateException: The page is already locked by 
    at ch.entwine.weblounge.common.impl.content.ResourceImpl.lock(ResourceImpl.java:848)
    at ch.entwine.weblounge.contentrepository.impl.operation.LockOperationImpl.apply(LockOperationImpl.java:83)
    at ch.entwine.weblounge.contentrepository.impl.AbstractWritableContentRepository.get(AbstractWritableContentRepository.java:322)
    at ch.entwine.weblounge.contentrepository.impl.AbstractWritableContentRepository.isLocked(AbstractWritableContentRepository.java:464)
    at ch.entwine.weblounge.contentrepository.fs.FileSystemContentRepositoryTest.testLock(FileSystemContentRepositoryTest.java:917)

Results :

Tests in error: 
  FileSystemContentRepositoryTest.testLock:917 ? IllegalState The page is alread...

Tests run: 90, Failures: 0, Errors: 1, Skipped: 4

[ERROR] There are test failures.

**Comment by myniva** [comment] 2016-04-18 16:06
duplicate of #369

**Closed as completed by myniva** 2016-04-18 16:06 UTC
Labels: bug
